name: noseph
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.6.9
  - pip:
    - bson==0.5.10
    - csbdeep==0.6.0
    - imagecodecs==2020.5.30
    - keras==2.3.1
    - numpy==1.19.1
    - pillow==7.1.2
    - scipy==1.5.0
    - tensorflow-gpu==1.14.0
    - tifffile==2020.9.3
    - tqdm==4.46.1
